"""Risk profile defaults."""

RISK_PROFILE_DEFAULTS = {
    "safe": {
        "max_position_size_pct": 8.0,
        "max_daily_trades": 2,
        "max_weekly_trades": 8,
        "etf_allowed": True,
        "rebalance_threshold": 4.0,
        "sector_concentration_limit": 20.0,
        "cash_reserve_pct": 12.0,
        "minimum_liquidity_volume": 1_000_000,
        "allow_queued_after_hours": True,
        "cooldown_minutes_per_ticker": 120,
        "allowed_tickers": [],
        "blocked_tickers": [],
        "aggressiveness": 25.0,
        "after_hours_news_scanning": True,
    },
    "balanced": {
        "max_position_size_pct": 12.0,
        "max_daily_trades": 4,
        "max_weekly_trades": 15,
        "etf_allowed": True,
        "rebalance_threshold": 5.0,
        "sector_concentration_limit": 25.0,
        "cash_reserve_pct": 7.5,
        "minimum_liquidity_volume": 750_000,
        "allow_queued_after_hours": True,
        "cooldown_minutes_per_ticker": 90,
        "allowed_tickers": [],
        "blocked_tickers": [],
        "aggressiveness": 50.0,
        "after_hours_news_scanning": True,
    },
    "risky": {
        "max_position_size_pct": 18.0,
        "max_daily_trades": 6,
        "max_weekly_trades": 25,
        "etf_allowed": True,
        "rebalance_threshold": 7.5,
        "sector_concentration_limit": 35.0,
        "cash_reserve_pct": 3.0,
        "minimum_liquidity_volume": 300_000,
        "allow_queued_after_hours": True,
        "cooldown_minutes_per_ticker": 45,
        "allowed_tickers": [],
        "blocked_tickers": [],
        "aggressiveness": 75.0,
        "after_hours_news_scanning": True,
    },
    "custom": {
        "max_position_size_pct": 10.0,
        "max_daily_trades": 3,
        "max_weekly_trades": 15,
        "etf_allowed": True,
        "rebalance_threshold": 5.0,
        "sector_concentration_limit": 25.0,
        "cash_reserve_pct": 5.0,
        "minimum_liquidity_volume": 500_000,
        "allow_queued_after_hours": True,
        "cooldown_minutes_per_ticker": 60,
        "allowed_tickers": [],
        "blocked_tickers": [],
        "aggressiveness": 50.0,
        "after_hours_news_scanning": True,
    },
}
